### ISSUE TITLE
Ticking Block Crash, Ritual of Peace

### ISSUE THREAD

**Issue by NillerMedDild** [TeamDman/Animus#60] opened 2018-06-12 07:32 UTC
Hey!

I crashed while running the Ritual of Peace. It was able to run for several minutes with no issue.
It might be worth mentioning that this crash occured on Enigmatica2Expert, which has Animania, so it could be an issue with spawning Animania peaceful mobs?

Crashlog: https://gist.github.com/NillerMedDild/66914b36bc86f6b324f30defc596cd67

Animus-2.0.1
BloodMagic-1.12.2-2.2.12-97

**Comment by Saereth** [comment] 2018-06-12 13:12
Thanks for the report, I pushed a fix for this, should be up on curseforge later today

**Comment by TeamDman** [comment] 2018-06-12 18:37
Fixed with latest build, you can grab it either from curseforge or from the releases tab here on github.

Issue was caused by the table of valid entities becoming null after a world reload, since the list was created when the ritual was activated, when the world is reloaded the ritual did not go through the reactivation sequence leaving the list null while the ritual starts ticking again. Most likely also happened involving chunk loading/unloading.

Added a null check that will repopulate the list. If the new list is empty, it will stop the ritual.

Thanks for reporting the issue!

**Closed by TeamDman** 2018-06-12 18:37 UTC
Labels: Fixed in Dev, bug

**Comment by NillerMedDild** [comment] 2018-06-12 20:00
Thanks for the quick fix!
